### PR TITLE
target/ppc: Implement cntlzdm/cnttzdm

### PR DESCRIPTION
**Pull request by lffpires**
Signed-off-by: Luis Pires <luis.pires@eldorado.org.br>

### CODE REVIEW

**Review by mferst — APPROVED** [review]
Maybe we should split it into two commits, but other than that LGTM.

**Comment by mferst** [comment]
BTW, it seems that `vclzdm`/`vctzdm` are the vector counterparts of `cntlzdm`/`cnttzdm`.

**Comment by lffpires** [comment]
> BTW, it seems that `vclzdm`/`vctzdm` are the vector counterparts of `cntlzdm`/`cnttzdm`.

Thanks! I'll add those!

**Review by billionai — APPROVED** [review]
LGTM

**Comment by mferst** [comment]
Merged in upstream.

**Pull request closed without merging**
