### PR TITLE
Alternative to PR #31

### PR DESCRIPTION
**Pull request by mferst**
We need a `REQUIRE_FLAGS2` because `REQUIRE_FLAGS_E(NONE, ...)` will always evaluate to false. Since no decodetree instruction requires insns_flag and insns_falgs2, drop `REQUIRE_FLAGS_E` for now.

### CODE REVIEW

**Comment by vcoracolombo** [comment]
I really liked this idea and I can already see it being useful for the other PRs I sent.

What do you think about having a macro that has both REQUIRE_INSNS_FLAGS2 and a REQUIRE_VSX or REQUIRE_VECTOR? In #51 and #54 I implemented a function whose only job is to call a helper, and used it to implement VSX instructions, and #52 has a very similar function but for VECTOR. Maybe we could merge them both if we have a macro like this.

**Comment by mferst** [comment]
We could have something like
```c
#define TRANS_FACILITY(FLAG, FAC, NAME, FUNC, ...) \
    static bool trans_##NAME(DisasContext *ctx, arg_##NAME *a) \
    {                                                          \
        REQUIRE_INSNS_FLAGS(ctx, FLAGS);                       \
        REQUIRE_##FAC(ctx);                                    \
        return FUNC(ctx, a, __VA_ARGS__);                      \
    }

#define TRANS_FACILITY2(FLAG2, FAC, NAME, FUNC, ...) \
    static bool trans_##NAME(DisasContext *ctx, arg_##NAME *a) \
    {                                                          \
        REQUIRE_INSNS_FLAGS2(ctx, FLAGS2);                     \
        REQUIRE_##FAC(ctx);                                    \
        return FUNC(ctx, a, __VA_ARGS__);                      \
    }
```
But that still wouldn't allow sharing code between #51/#54 and #52 as the argument types are different (`arg_XX3` and `arg_VX`).

**Comment by vcoracolombo** [comment]
> We could have something like
> 
> ```c
> #define TRANS_FACILITY(FLAG, FAC, NAME, FUNC, ...) \
>     static bool trans_##NAME(DisasContext *ctx, arg_##NAME *a) \
>     {                                                          \
>         REQUIRE_INSNS_FLAGS(ctx, FLAGS);                       \
>         REQUIRE_##FAC(ctx);                                    \
>         return FUNC(ctx, a, __VA_ARGS__);                      \
>     }
> 
> #define TRANS_FACILITY2(FLAG2, FAC, NAME, FUNC, ...) \
>     static bool trans_##NAME(DisasContext *ctx, arg_##NAME *a) \
>     {                                                          \
>         REQUIRE_INSNS_FLAGS2(ctx, FLAGS2);                     \
>         REQUIRE_##FAC(ctx);                                    \
>         return FUNC(ctx, a, __VA_ARGS__);                      \
>     }
> ```

I think this is great

> But that still wouldn't allow sharing code between #51/#54 and #52 as the argument types are different (`arg_XX3` and `arg_VX`).

Indeed, what I was thinking was something like:

```
static bool do_helper_VX(arg_VX *a,
        void (*helper)(TCGv_ptr, TCGv_ptr, TCGv_ptr, TCGv_ptr))
{
    TCGv_ptr vrt, vra, vrb;

    vrt = gen_avr_ptr(a->vrt);
    vra = gen_avr_ptr(a->vra);
    vrb = gen_avr_ptr(a->vrb);

    helper(cpu_env, vrt, vra, vrb);

    tcg_temp_free_ptr(vrt);
    tcg_temp_free_ptr(vra);
    tcg_temp_free_ptr(vrb);

    return true;
}

TRANS_FACILITY2(ISA310, VSX, XSCMPEQQP, do_helper_VX, gen_helper_xscmpeqqp)
TRANS_FACILITY2(ISA310, VSX, XSCMPEQQP, do_helper_VX, gen_helper_xscmpeqqp)
TRANS_FACILITY2(ISA310, VSX, XSCMPEQQP, do_helper_VX, gen_helper_xscmpeqqp)
TRANS_FACILITY2(ISA310, VECTOR, VDIVSW, do_helper_VX, gen_helper_VDIVSW)
TRANS_FACILITY2(ISA310, VECTOR, VDIVUW, do_helper_VX, gen_helper_VDIVUW)
TRANS_FACILITY2(ISA310, VECTOR, VDIVSD, do_helper_VX, gen_helper_VDIVSD)
TRANS_FACILITY2(ISA310, VECTOR, VDIVUD, do_helper_VX, gen_helper_VDIVUD)
TRANS_FACILITY2(ISA310, VECTOR, VDIVSQ, do_helper_VX, gen_helper_VDIVSQ)
TRANS_FACILITY2(ISA310, VECTOR, VDIVUQ, do_helper_VX, gen_helper_VDIVUQ)
```

And having another one for `XX3`.

**Comment by mferst** [comment]
Aren't these X-form? VX-form instructions don't have the least significant bit reserved.

**Comment by vcoracolombo** [comment]
> Aren't these X-form? VX-form instructions don't have the least significant bit reserved.

Oh, that's embarrassing. You're right, I mistakenly thought they were the same thing and didn't notice the difference.

**Comment by mferst** [comment]
Nothing to be embarrassed about, instruction formats in PowerISA are pretty confusing :)
We still could use your approach, but we'd need to open the argument struct, e.g.:
```c
static bool do_avr_helper3(int t, int a, int b,
        void (*helper)(TCGv_ptr, TCGv_ptr, TCGv_ptr, TCGv_ptr))
{
    TCGv_ptr vrt, vra, vrb;

    vrt = gen_avr_ptr(t);
    vra = gen_avr_ptr(a);
    vrb = gen_avr_ptr(b);

    helper(cpu_env, vrt, vra, vrb);

    tcg_temp_free_ptr(vrt);
    tcg_temp_free_ptr(vra);
    tcg_temp_free_ptr(vrb);

    return true;
}

static bool do_avr_helper_VX(arg_VX *a,
        void (*helper)(TCGv_ptr, TCGv_ptr, TCGv_ptr, TCGv_ptr))
{
    return do_avr_helper3(a->vrt, a->vra, a->vrb, helper);
}

static bool do_avr_helper_XX3(arg_XX3 *a,
        void (*helper)(TCGv_ptr, TCGv_ptr, TCGv_ptr, TCGv_ptr))
{
    return do_avr_helper3(a->xt, a->xa, a->xb, helper);
}

static bool do_avr_helper_X(arg_X *a,
        void (*helper)(TCGv_ptr, TCGv_ptr, TCGv_ptr, TCGv_ptr))
{
    return do_avr_helper3(a->rt, a->ra, a->rb, helper);
}

TRANS_FACILITY2(ISA310, VSX, XSCMPEQQP, do_avr_helper_X, gen_helper_XSCMPEQQP)
/* ... */
TRANS_FACILITY2(ISA310, VECTOR, VDIVSW, do_helper_VX, gen_helper_VDIVSW)
/* ... */
TRANS_FACILITY2(ISA300, VSX, XSMAXCDP, gen_helper_XSMAXCDP)
/* ... */
```
For now, it seems too much work to share a small piece of code, but let's keep an eye for other places where these macros can be useful.

**Review by vcoracolombo — APPROVED** [review]

**Comment by mferst** [comment]
Merged in upstream: https://lists.gnu.org/archive/html/qemu-ppc/2022-03/msg00002.html

**Pull request closed without merging**
