### PR TITLE
Macros to check privilege level in decodetree methods

### PR DESCRIPTION
**Pull request by mferst**
This PR is the suggestion that first appeared in #88, and serves as an alternative to #92 and the `do_check_sv` method of #66.

### CODE REVIEW

**Review by luporl — APPROVED** [review]
LGTM!

**Comment by lrcoutinho** [comment]
LGTM! I prefer this one, cause both CHK_HV and GEN_PRIV could be used with return value

**Review by lrcoutinho — APPROVED** [review]
LGTM!

**Comment by mferst** [comment]
#92 won

**Pull request closed without merging**
